### ISSUE TITLE
how to deploy to the devnet?

### ISSUE THREAD

**Issue by javamr123** [solana-labs/solana-solidity.js#20]
how to deploy to the "https://api.devnet.solana.com"?

**Comment by javamr123** [comment]
my solana --version
solana-cli 1.8.2 (src:42a2c292; feat:52865992)

**Comment by seanyoung** [comment]
There are some features waiting to be activated on devnet:

```
$ solana -u devnet feature status | grep -e return_data -e log_data -e ed25519
BJVXq6NdLC7jCDGjfqJv7M1XHD4Y13VrpDqRF2U7UBcC | inactive                    | enable sol_{set,get}_return_data syscall
E1TvTNipX8TKNHrhRC8SMuAwQmGY58TZ4drdztP3Gxwc | inactive                    | enable builtin ed25519 signature verify program
HYPs7jyJ3KwQFdDpuSzMtVKf1MLJDaZRv3CSWvfUqdFo | inactive                    | enable sol_log_data syscall
```

I wrote these features and totally messed up the keys for enabling the features. 🤦‍♂️ So these are going to have to get new feature keys. This is already in the next release so we just need to wait for that to be enabled.

**Comment by Abubakar672** [comment]
I am facing this error while deploying the contract on dev net, Although i have around 13 sol tokens in my account 

{'code': -32002, 'message': 'Transaction simulation failed: Attempt to debit an account but found no record of a prior credit.', 'data': {'accounts': None, 'err': 'AccountNotFound', 'logs': []}}

Is there any solution

**Comment by seanyoung** [comment]
@Abubakar672 the error looks like there is an airdrop attempted to account for more than 1 SOL, which is not allowed.

What exactly are you running?

**Comment by javamr123** [comment]
> 

Can it be deployed on the mainnet?

**Comment by javamr123** [comment]
> 有一些功能等待在 devnet 上激活：
> 
> ```
> $ solana -u devnet feature status | grep -e return_data -e log_data -e ed25519
> BJVXq6NdLC7jCDGjfqJv7M1XHD4Y13VrpDqRF2U7UBcC | inactive                    | enable sol_{set,get}_return_data syscall
> E1TvTNipX8TKNHrhRC8SMuAwQmGY58TZ4drdztP3Gxwc | inactive                    | enable builtin ed25519 signature verify program
> HYPs7jyJ3KwQFdDpuSzMtVKf1MLJDaZRv3CSWvfUqdFo | inactive                    | enable sol_log_data syscall
> ```
> 
> 我编写了这些功能并且完全弄乱了启用这些功能的键。🤦‍♂️所以这些将不得不获得新的功能键。这已经在下一个版本中了，所以我们只需要等待它被启用。

Can it be deployed on the mainnet?

**Comment by javamr123** [comment]
> There are some features waiting to be activated on devnet:
> 
> ```
> $ solana -u devnet feature status | grep -e return_data -e log_data -e ed25519
> BJVXq6NdLC7jCDGjfqJv7M1XHD4Y13VrpDqRF2U7UBcC | inactive                    | enable sol_{set,get}_return_data syscall
> E1TvTNipX8TKNHrhRC8SMuAwQmGY58TZ4drdztP3Gxwc | inactive                    | enable builtin ed25519 signature verify program
> HYPs7jyJ3KwQFdDpuSzMtVKf1MLJDaZRv3CSWvfUqdFo | inactive                    | enable sol_log_data syscall
> ```
> 
> I wrote these features and totally messed up the keys for enabling the features. 🤦‍♂️ So these are going to have to get new feature keys. This is already in the next release so we just need to wait for that to be enabled.

Can it be deployed on the mainnet?

**Comment by seanyoung** [comment]
> Can it be deployed on the mainnet?

Yes:
```
$ solana -u mainnet-beta feature status | grep -e return_data -e log_data -e ed25519
6ppMXNYLhVd7GcsZ5uV11wQEW7spppiMVfqQv5SXhDpX | active since slot 117936008 | enable builtin ed25519 signature verify program
6uaHcKPGUy4J7emLBgUTeufhJdiwhngW6a1R9B7c2ob9 | active since slot 117936008 | enable sol_log_data syscall
DwScAzPUjuv65TMbDnFY7AgwmotzWy3xpEJMXM3hZFaB | active since slot 117936008 | enable sol_{set,get}_return_data syscall
```

**Comment by javamr123** [comment]
> 

I use the erc20 token written in solidity to deploy to solana with this tool, is my token still recognized?

**Comment by javamr123** [comment]
> > Can it be deployed on the mainnet?
> 
> Yes:
> 
> ```
> $ solana -u mainnet-beta feature status | grep -e return_data -e log_data -e ed25519
> 6ppMXNYLhVd7GcsZ5uV11wQEW7spppiMVfqQv5SXhDpX | active since slot 117936008 | enable builtin ed25519 signature verify program
> 6uaHcKPGUy4J7emLBgUTeufhJdiwhngW6a1R9B7c2ob9 | active since slot 117936008 | enable sol_log_data syscall
> DwScAzPUjuv65TMbDnFY7AgwmotzWy3xpEJMXM3hZFaB | active since slot 117936008 | enable sol_{set,get}_return_data syscall
> ```

I use the erc20 token written in solidity to deploy to solana with this tool, is my token still recognized?

**Comment by seanyoung** [comment]
> I use the erc20 token written in solidity to deploy to solana with this tool, is my token still recognized?

You can deploy an erc20 solidity contract on Solana and it will work as a contract. However Solana uses spl-token for tokens (I'm working on spl-token compatibility right now). Does that help?

https://github.com/hyperledger-labs/solang/issues/607

**Comment by javamr123** [comment]
> > I use the erc20 token written in solidity to deploy to solana with this tool, is my token still recognized?
> 
> You can deploy an erc20 solidity contract on Solana and it will work as a contract. However Solana uses spl-token for tokens (I'm working on spl-token compatibility right now). Does that help?
> 
> [hyperledger-labs/solang#607](https://github.com/hyperledger-labs/solang/issues/607)

I don't seem to understand the content of your reply in hyperledger-labs/solang#607. But I think some solidity plugin might need to be done to achieve the following 2 functions:
1. Solidity can receive spl-token.
2. Solidity can transfer spl-token.
3. Solidity can call all functions of spl-token, similar to the communication between solidity and rust, solidity can call rust methods

**Comment by seanyoung** [comment]
> I don't seem to understand the content of your reply in [hyperledger-labs/solang#607](https://github.com/hyperledger-labs/solang/issues/607). But I think some solidity plugin might need to be done to achieve the following 2 functions:
> 
>     1. Solidity can receive spl-token.
> 
>     2. Solidity can transfer spl-token.
> 
>     3. Solidity can call all functions of spl-token, similar to the communication between solidity and rust, solidity can call rust methods

Yes, you are right. We currently working on exactly this.

**Comment by javamr123** [comment]
> > I don't seem to understand the content of your reply in [hyperledger-labs/solang#607](https://github.com/hyperledger-labs/solang/issues/607). But I think some solidity plugin might need to be done to achieve the following 2 functions:
> > ```
> > 1. Solidity can receive spl-token.
> > 
> > 2. Solidity can transfer spl-token.
> > 
> > 3. Solidity can call all functions of spl-token, similar to the communication between solidity and rust, solidity can call rust methods
> > ```
> 
> Yes, you are right. We currently working on exactly this.

Thank you, these functions are very practical and important for the start of the business. If you have finished developing it, I hope you will take the initiative to notify me to close this issue, thank you again!

**Comment by bhawikyudiz** [comment]
I am facing this issue while calling contract function.
![Uploading Screenshot 2022-09-27 at 12.25.13 PM.png…]()

TypeError: Cannot read properties of undefined (reading 'numRequiredSignatures')
    at Function.populate (/Users/yudiz-bhawik/Documents/solana-solidity.js/node_modules/@solana/web3.js/lib/index.cjs.js:1979:24)
    at Connection.simulateTransaction (/Users/yudiz-bhawik/Documents/solana-solidity.js/node_modules/@solana/web3.js/lib/index.cjs.js:6538:33)
    at /Users/yudiz-bhawik/Documents/solana-solidity.js/node_modules/@solana/solidity/lib/logs.js:98:41
    at Generator.next (<anonymous>)
    at /Users/yudiz-bhawik/Documents/solana-solidity.js/node_modules/@solana/solidity/lib/logs.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/yudiz-bhawik/Documents/solana-solidity.js/node_modules/@solana/solidity/lib/logs.js:4:12)
    at simulateTransactionWithLogs (/Users/yudiz-bhawik/Documents/solana-solidity.js/node_modules/@solana/solidity/lib/logs.js:97:12)
    at Contract.<anonymous> (/Users/yudiz-bhawik/Documents/solana-solidity.js/node_modules/@solana/solidity/lib/contract.js:372:64)
    at Generator.next (<anonymous>)

**Comment by bhawikyudiz** [comment]
I am facing this error while calling smart contract function.

TypeError: Cannot read properties of undefined (reading 'numRequiredSignatures')
    at Function.populate (/Users/bhawik/Documents/solana-solidity.js/node_modules/@solana/web3.js/lib/index.cjs.js:1979:24)
    at Connection.simulateTransaction (/Users/yudiz-bhawik/Documents/solana-solidity.js/node_modules/@solana/web3.js/lib/index.cjs.js:6538:33)
    at /Users/bhawik/Documents/solana-solidity.js/node_modules/@solana/solidity/lib/logs.js:98:41
    at Generator.next (<anonymous>)
    at /Users/bhawik/Documents/solana-solidity.js/node_modules/@solana/solidity/lib/logs.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/bhawik/Documents/solana-solidity.js/node_modules/@solana/solidity/lib/logs.js:4:12)
    at simulateTransactionWithLogs (/Users/yudiz-bhawik/Documents/solana-solidity.js/node_modules/@solana/solidity/lib/logs.js:97:12)
    at Contract.<anonymous> (/Users/yudiz-bhawik/Documents/solana-solidity.js/node_modules/@solana/solidity/lib/contract.js:372:64)
    at Generator.next (<anonymous>)

**Comment by seanyoung** [comment]
> I am facing this error while calling smart contract function.
> 
> TypeError: Cannot read properties of undefined (reading 'numRequiredSignatures') at Function.populate (/Users/bhawik/Documents/solana-solidity.js/node_modules/@solana/web3.js/lib/index.cjs.js:1979:24) at Connection.simulateTransaction (/Users/yudiz-bhawik/Documents/solana-solidity.js/node_modules/@solana/web3.js/lib/index.cjs.js:6538:33) at /Users/bhawik/Documents/solana-solidity.js/node_modules/@solana/solidity/lib/logs.js:98:41 at Generator.next () at /Users/bhawik/Documents/solana-solidity.js/node_modules/@solana/solidity/lib/logs.js:8:71 at new Promise () at __awaiter (/Users/bhawik/Documents/solana-solidity.js/node_modules/@solana/solidity/lib/logs.js:4:12) at simulateTransactionWithLogs (/Users/yudiz-bhawik/Documents/solana-solidity.js/node_modules/@solana/solidity/lib/logs.js:97:12) at Contract. (/Users/yudiz-bhawik/Documents/solana-solidity.js/node_modules/@solana/solidity/lib/contract.js:372:64) at Generator.next ()

Hi @bhawikyudiz can you please show us exactly what you are running. Thanks!
