### ISSUE TITLE
Cannot run view methods

### ISSUE THREAD

**Issue by cawabunga** [solana-labs/solana-solidity.js#30]
I'm trying to run the example, but I've faced an issue during running "read" methods of the contract. I tried to deploy simple contract, unfortunately it didn't work as well. Unlike read methods, write methods are working well. Can anybody show a direction to dig?

Environment:
Node: 16 and 18
Solang: v0.1.12
@solana/solidity: v0.0.20
@solana/web3.js: 1.30.2 and 1.43.4

```bash
node scripts/deploy-contracts.js
```
```
Connecting to your local Solana node ...
Airdropping SOL to a new wallet ...
Deploying the Solang-compiled ERC20 program ...
Program deployment finished, deploying the ERC20 contract ...
Contract deployment finished, invoking some contract functions ...
/Users/user/solana-example/node_modules/@solana/web3.js/lib/index.cjs.js:3073
    if (message.header.numRequiredSignatures > 0) {
                       ^

TypeError: Cannot read properties of undefined (reading 'numRequiredSignatures')
    at Function.populate (/Users/user/solana-example/node_modules/@solana/web3.js/lib/index.cjs.js:3073:24)
    at Connection.simulateTransaction (/Users/user/solana-example/node_modules/@solana/web3.js/lib/index.cjs.js:7278:33)
    at /Users/user/solana-example/node_modules/@solana/solidity/lib/logs.js:98:41
    at Generator.next (<anonymous>)
    at /Users/user/solana-example/node_modules/@solana/solidity/lib/logs.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/user/solana-example/node_modules/@solana/solidity/lib/logs.js:4:12)
    at simulateTransactionWithLogs (/Users/user/solana-example/node_modules/@solana/solidity/lib/logs.js:97:12)
    at Contract.<anonymous> (/Users/user/solana-example/node_modules/@solana/solidity/lib/contract.js:372:64)
    at Generator.next (<anonymous>)
```

**Comment by cawabunga** [comment]
Magic happened, all worked after reinstalling dependencies.
