### ISSUE TITLE
ERC20 example does not work -- deploy fails

### ISSUE THREAD

**Issue by wolfflow** [solana-labs/solana-solidity.js#45]
Tried to deploy [ERC20.sol example](https://github.com/solana-labs/solana-solidity.js/blob/master/test/examples/erc20/contracts/ERC20.sol)

**Steps to reproduce**
`node ERC20.js`

```
Connecting to your local Solana node ...
Airdropping SOL to a new wallet ...
Deploying the Solang-compiled ERC20 program ...
Program deployment finished, deploying the ERC20 contract ...
Transaction simulation failed: Error processing Instruction 1: invalid program argument
    Program 11111111111111111111111111111111 invoke [1]
    Program 11111111111111111111111111111111 success
    Program Hn9KXdnBK6h2A7vZ2YqnnQdqzh8zv92qQsAEBHSHqv7j invoke [1]
    Program Hn9KXdnBK6h2A7vZ2YqnnQdqzh8zv92qQsAEBHSHqv7j consumed 550 of 400000 compute units
    Program Hn9KXdnBK6h2A7vZ2YqnnQdqzh8zv92qQsAEBHSHqv7j failed: invalid program argument
/Users/xf/Work/mycompany/_research/crypto/solana-apps/solana-solidity.js/node_modules/@solana/solidity/lib/logs.js:162
            ? new errors_1.TransactionError(failedMatch[2])
              ^

TransactionError: invalid program argument
    at parseTransactionError (/Users/xf/Work/mycompany/_research/crypto/solana-apps/solana-solidity.js/node_modules/@solana/solidity/lib/logs.js:162:15)
    at /Users/xf/Work/mycompany/_research/crypto/solana-apps/solana-solidity.js/node_modules/@solana/solidity/lib/logs.js:123:27
    at Generator.throw (<anonymous>)
    at rejected (/Users/xf/Work/mycompany/_research/crypto/solana-apps/solana-solidity.js/node_modules/@solana/solidity/lib/logs.js:6:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  logs: [
    'Program 11111111111111111111111111111111 invoke [1]',
    'Program 11111111111111111111111111111111 success',
    'Program Hn9KXdnBK6h2A7vZ2YqnnQdqzh8zv92qQsAEBHSHqv7j invoke [1]',
    'Program Hn9KXdnBK6h2A7vZ2YqnnQdqzh8zv92qQsAEBHSHqv7j consumed 550 of 400000 compute units',
    'Program Hn9KXdnBK6h2A7vZ2YqnnQdqzh8zv92qQsAEBHSHqv7j failed: invalid program argument'
  ],
  computeUnitsUsed: 550
}
```

**Comment by AliceInHunterland** [comment]
Same issue with https://github.com/hyperledger/solang#build-for-solana flipper example.
